#inc
noinst_HEADERS= AbstractComChannel.hh \
                AbstractInterp4Command.hh \
                AbstractMobileObj.hh \
                AbstractScene.hh \
                ComChannel.hh \
                CommandsParser.hh \
                Configuration.hh \
                geomVector.hh \
                LibInterface.hh \
                MobileObject.hh \
                preprocessor.hh \
                ProgramInterpreter.hh \
                Scene.hh \
                Set4LibInterfaces.hh \
                Vector3D.hh \
                xmlinterp.hh \
                Interp4Move.hh \
                Interp4Set.hh \
                Interp4Pause.hh \
                Interp4Rotate.hh